### ISSUE TITLE
Caching queue connection

### ISSUE THREAD

**Issue by jfaraklit** [lloydcotten/common-mq#34]
mq.connect(...). Is this caching the connection for subsequent messages? Looking in a use case where messages are going to different queues based on message content and similar message types should not connect again and use the existing connection (somehow).

**Comment by jfaraklit** [comment]
ah. seems like `mp.connect (...)` is not actually making any connection but setting the required attributes of `mq ` object for publishing messages later. Am I missing anything in here?

**Comment by lloydcotten** [comment]
This depends on the provider.  The pattern is to do an `initProvider` (at the end of the event loop) from the provider constructor - which is what happens on `mq.connect`. 

For sqs provider this is simply to setup the queue url and create the queue if it doesn't already exist.

For others, like amqp, it actually does open the connection for subsequent use.

Hope that helps clarify it for you.

**Comment by jfaraklit** [comment]
Yeah. I was talking about SQS. Thanks
